### ISSUE TITLE
Feature Request: Run service for every button

### ISSUE THREAD

**Issue by marrobHD** [custom-cards/roku-card#12]
Feature Request: Run service for every button like skip, left arrow, right arrow, down arrow, up arrow, enter, back, home, info, forward, backwards, pause/play
Thanks
```
power:
  service: broadlink.send
  service_data:
    host: 192.168.178.73
    packet: JgBGAJKWEjcSOBE5ERMTEhITEhMSExI4ETgSOBEUERQRFBEUERQRORE4EjgSNxMSEhMSExITEhMRFBITERQSOBE4EjgSNxIADQUAAA==

```
So i mean it. That is how I use it. Please add it to skip, left arrow, right arrow, down arrow, up arrow, enter, back, home, info, forward, backwards, pause and play.
Thanks
