### ISSUE TITLE
No card type configured

### ISSUE THREAD

**Issue by mheppner** [custom-cards/roku-card#15]
Not sure what's going on here, but I can't get this card to load. I have other custom cards loaded without issue.

- `home-assistant-frontend==20190626.0`
- `homeassistant==0.95.4`
- custom-cards/roku-card@0.0.6
- Firefox 68 and latest Chrome

The manual card I added:

```yaml
      - type: custom:roku-card
        entity: media_player.tv
        name: TV
        tv: true
        power:
          service: switch.turn_on
          service_data:
            entity_id: switch.tv
```

In the ui-lovelace.yaml, along with other custom module script resources:

```yaml
  - type: module
    url: /local/roku-card.js?v=0
```

I have verified that `https://<my domain>/local/roku-card.js` is accessible and is returning the JS. In the FF console, I can also see that the element has been loaded:

```js
> customElements.get("roku-card")
function RokuCard()
```

No other errors are shown. Same problem in Chrome and Firefox on different devices, with cache being cleared.

When editing the card through the UI, I do get an error:

```
get-card-element-tag.ts:4
Uncaught (in promise) TypeError: Cannot read property 'startsWith' of undefined
    at h (get-card-element-tag.ts:4)
    at HTMLElement.value (hui-edit-card.ts:336)
    at HTMLElement.value (hui-edit-card.ts:123)
    at HTMLElement.performUpdate (updating-element.ts:716)
    at HTMLElement._enqueueUpdate (updating-element.ts:649)
```
