### ISSUE TITLE
Cannot access source_list

### ISSUE THREAD

**Issue by mheppner** [custom-cards/roku-card#19]
- home-assistant-frontend==20190805.0
- homeassistant==0.97.2
- latest roku-card 30b1141

In the latest version of HA, I don't think the sources are being sent anymore.

Error:
```
Uncaught (in promise) TypeError: Cannot read property 'indexOf' of undefined
    at HTMLElement.render (roku-card.js?v=2:55)
```

Context of where error happens:
```
              <paper-listbox
                slot="dropdown-content"
                .selected="${
                  stateObj.attributes.source_list.indexOf(        <-- source_list is undefined
                    stateObj.attributes.source
                  )
                }"
              >
```

Looking at the value from `const stateObj = this.hass.states[this._config.entity]`:
```
stateObj:
  attributes:
    friendly_name: "TV"
    supported_features: 19388
    __proto__: Object
  context:
    id: "a8c32d121b0146e1b1972d5028e98163"
    parent_id: null
    user_id: null
    __proto__: Object
  entity_id: "media_player.tv"
  last_changed: "2019-08-15T15:46:39.735648+00:00"
  last_updated: "2019-08-15T15:46:39.735648+00:00"
  state: "off"
```
