### ISSUE TITLE
roku-card - roku-card-editor clash?

### ISSUE THREAD

**Issue by bmorgan99** [custom-cards/roku-card#9]
When I try to edit a roku card I get "'CustomElementRegistry': this name has already been used with this registry" and can't.  If I remove roku-card-editor from resources I can edit with no error.

Maybe a separate issue, but when I create a popup-card, the syntax seems to be accepted but the card doesn't appear in lovelace except in edit mode.  No log or browser errors.

This is also in my log, not sure of the culprit:
http://192.168.1.9:8123/lovelace/10:0:0 Uncaught

```
resources:
  - type: js
    url: /local/card-tools.js?v=6
  - type: js
    url: /local/popup-card.js?v=6
  - type: module
    url: /local/roku-card-editor.js?v=6
  - type: js
    url: /local/roku-card.js?v=6
```

```
card:
  entities:
    - entity: media_player.roku_kitchen
      icon: 'mdi:alpha-r-box-outline'
      name: Kitchen
  type: entities
entity: media_player.roku_kitchen
title: Kitchen Roku
type: 'custom:popup-card'
```
```
entity: media_player.roku_kitchen
name: Kitchen Roku
theme: darkcyan
type: 'custom:roku-card'
```

HA 0.87.1, hassos 2.8
