### ISSUE TITLE
App Image: Option Not working

### ISSUE THREAD

**Issue by AngeloAna** [custom-cards/roku-card#94]
I am trying to use a PNG picture to show it the left App button. I downloaded one that is about 1K and put it in the www folder in a new subfolder called icons. I added the following image: YAML line and the picture does not show.

```
apps:
  - image: /local/icons/sling.png
    app: Sling
```

Does the image need to be a certain size?

**Comment by Fat-Knees** [comment]
Struggling also

**Comment by Fat-Knees** [comment]
So apparently "/local" directs to the "/homeassistant/www"

With that being said. you need to copy the path from "/www" 
Replace "/www" with "/local"

I created an "images" folder inside the "roku-card" folder.

an example of my card YAML with a working image is as follows 

```
type: custom:roku-card
entity: media_player.livingroom_roku
apps:
  - image: /local/community/roku-card/images/hulu1.jpg
    app: Hulu
```

**Comment by Fat-Knees** [comment]
you are also able to put in a web address.

```
type: custom:roku-card
entity: media_player.livingroom_roku
apps:
  - image: https://download.logo.wine/logo/Hulu/Hulu-Logo.wine.png
    app: Hulu
```
